import { NextResponse } from "next/server";

type Report = {
  problemBreakdown: string;
  stakeholders: string;
  solution: string;
  actionPlan: string;
};

export async function POST(req: Request) {
  try {
    const { reportData } = await req.json();
    const { report, problemStatement, timestamp } = reportData;

    // Generate HTML content
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Strategic Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      margin: 0;
      padding: 20px;
      background: white;
    }
    .cover {
      text-align: center;
      padding: 60px 20px;
      border-bottom: 2px solid #1e40af;
      margin-bottom: 40px;
    }
    .cover h1 {
      color: #1e40af;
      font-size: 32px;
      margin: 0 0 20px 0;
    }
    .cover p {
      font-size: 16px;
      color: #666;
      margin: 10px 0;
    }
    .section {
      margin-bottom: 40px;
      page-break-inside: avoid;
    }
    .section h2 {
      color: #1e40af;
      font-size: 20px;
      border-bottom: 2px solid #1e40af;
      padding-bottom: 10px;
      margin-top: 30px;
      page-break-after: avoid;
    }
    .section-content {
      margin-top: 15px;
    }
    .bullet {
      margin-left: 20px;
      margin-bottom: 8px;
    }
    .bullet::before {
      content: "• ";
      color: #1e40af;
      font-weight: bold;
      margin-right: 8px;
    }
    .number {
      margin-left: 20px;
      margin-bottom: 8px;
    }
    .number::before {
      content: counter(item) ". ";
      color: #1e40af;
      font-weight: bold;
      counter-increment: item;
    }
    .heading {
      font-weight: bold;
      margin-top: 15px;
      margin-bottom: 8px;
      color: #333;
    }
    .paragraph {
      margin-bottom: 12px;
    }
    .footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      color: #999;
      font-size: 12px;
    }
    @media print {
      body { margin: 0; padding: 0; }
      .section { page-break-inside: avoid; }
      .section h2 { page-break-after: avoid; }
    }
  </style>
</head>
<body>
  <div class="cover">
    <h1>Strategic Planning Report</h1>
    <p><strong>${escapeHtml(problemStatement)}</strong></p>
    <p>Generated: ${new Date(timestamp).toLocaleDateString()}</p>
  </div>

  <div class="section">
    <h2>Problem Breakdown</h2>
    <div class="section-content">
      ${formatContent(report.problemBreakdown)}
    </div>
  </div>

  <div class="section">
    <h2>Key Stakeholders</h2>
    <div class="section-content">
      ${formatContent(report.stakeholders)}
    </div>
  </div>

  <div class="section">
    <h2>Solution Approach</h2>
    <div class="section-content">
      ${formatContent(report.solution)}
    </div>
  </div>

  <div class="section">
    <h2>Action Plan</h2>
    <div class="section-content">
      ${formatContent(report.actionPlan)}
    </div>
  </div>

  <div class="footer">
    <p>Generated by AI Planning Agent • Strategic planning made simple</p>
  </div>
</body>
</html>
    `;

    // Return the HTML as a blob that can be converted to PDF on client
    return new Response(htmlContent, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `inline; filename="report-${Date.now()}.html"`,
      },
    });
  } catch (error) {
    console.error("PDF export error:", error);
    return NextResponse.json(
      { error: "Export failed", success: false },
      { status: 500 }
    );
  }
}

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

function formatContent(content: string): string {
  const lines = content.split("\n").filter((line) => line.trim());
  let html = "";
  let inNumberedList = false;
  let numberCounter = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    const escaped = escapeHtml(trimmed);

    // Heading (ends with :)
    if (escaped.endsWith(":") && escaped.length > 2) {
      html += `<div class="heading">${escaped}</div>`;
      inNumberedList = false;
    }
    // Bullet point
    else if (escaped.startsWith("•") || escaped.startsWith("-")) {
      const text = escaped.replace(/^[•-]\s*/, "");
      html += `<div class="bullet">${text}</div>`;
      inNumberedList = false;
    }
    // Numbered item
    else if (/^\d+\.\s/.test(escaped)) {
      const text = escaped.replace(/^\d+\.\s*/, "");
      html += `<div class="number">${text}</div>`;
    }
    // Regular paragraph
    else {
      html += `<div class="paragraph">${escaped}</div>`;
      inNumberedList = false;
    }
  }

  return html;
}
