import { NextResponse } from "next/server";

type Report = {
  problemBreakdown: string;
  stakeholders: string;
  solution: string;
  actionPlan: string;
};

export async function POST(req: Request) {
  try {
    const { reportData } = await req.json();
    const { report, problemStatement, timestamp } = reportData;

    // Generate HTML content
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Strategic Report</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', sans-serif;
      line-height: 1.6;
      color: #333;
      background: white;
      padding: 40px 20px;
    }
    
    .container {
      max-width: 900px;
      margin: 0 auto;
    }
    
    .cover {
      text-align: center;
      padding: 60px 20px;
      border-bottom: 3px solid #1e40af;
      margin-bottom: 60px;
    }
    
    .cover h1 {
      color: #1e40af;
      font-size: 36px;
      font-weight: 700;
      margin-bottom: 25px;
      line-height: 1.3;
    }
    
    .cover p {
      font-size: 16px;
      color: #555;
      margin: 15px 0;
      line-height: 1.6;
    }
    
    .cover .timestamp {
      font-size: 13px;
      color: #999;
      margin-top: 20px;
    }
    
    .section {
      margin-bottom: 50px;
      page-break-inside: avoid;
    }
    
    .section h2 {
      color: #1e40af;
      font-size: 24px;
      font-weight: 700;
      border-bottom: 2px solid #1e40af;
      padding-bottom: 12px;
      margin-bottom: 25px;
      margin-top: 40px;
      page-break-after: avoid;
    }
    
    .section-content {
      margin-top: 15px;
    }
    
    .bullet-item {
      margin-left: 0;
      margin-bottom: 15px;
      padding-left: 24px;
      position: relative;
      line-height: 1.7;
      font-size: 15px;
    }
    
    .bullet-item::before {
      content: "•";
      color: #1e40af;
      font-weight: bold;
      font-size: 20px;
      position: absolute;
      left: 0;
      top: -2px;
    }
    
    .number-item {
      margin-left: 0;
      margin-bottom: 16px;
      padding-left: 28px;
      position: relative;
      line-height: 1.7;
      font-size: 15px;
      counter-increment: item;
    }
    
    .number-item::before {
      content: counter(item) ".";
      color: #1e40af;
      font-weight: bold;
      position: absolute;
      left: 0;
      min-width: 24px;
    }
    
    .heading-item {
      font-weight: 700;
      margin-top: 20px;
      margin-bottom: 12px;
      color: #333;
      font-size: 15px;
      page-break-after: avoid;
    }
    
    .paragraph {
      margin-bottom: 15px;
      line-height: 1.7;
      font-size: 15px;
    }
    
    .footer {
      margin-top: 80px;
      padding-top: 30px;
      border-top: 1px solid #ddd;
      text-align: center;
      color: #999;
      font-size: 12px;
    }
    
    @media print {
      body {
        margin: 0;
        padding: 20px;
      }
      .container {
        max-width: 100%;
      }
      .section {
        page-break-inside: avoid;
      }
      .section h2 {
        page-break-after: avoid;
      }
      .heading-item {
        page-break-after: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="cover">
      <h1>Strategic Planning Report</h1>
      <p><strong>${escapeHtml(problemStatement)}</strong></p>
      <p class="timestamp">Generated: ${new Date(timestamp).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    </div>

    <div class="section">
      <h2>Problem Breakdown</h2>
      <div class="section-content">
        ${formatContent(report.problemBreakdown, 'problem')}
      </div>
    </div>

    <div class="section">
      <h2>Key Stakeholders</h2>
      <div class="section-content">
        ${formatContent(report.stakeholders, 'stakeholders')}
      </div>
    </div>

    <div class="section">
      <h2>Solution Approach</h2>
      <div class="section-content">
        ${formatContent(report.solution, 'solution')}
      </div>
    </div>

    <div class="section">
      <h2>Action Plan</h2>
      <div class="section-content" style="counter-reset: item;">
        ${formatContent(report.actionPlan, 'action')}
      </div>
    </div>

    <div class="footer">
      <p>Generated by AI Planning Agent • Strategic planning made simple</p>
    </div>
  </div>
</body>
</html>
    `;

    // Return the HTML as a blob that can be converted to PDF on client
    return new Response(htmlContent, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `inline; filename="report-${Date.now()}.html"`,
      },
    });
  } catch (error) {
    console.error("PDF export error:", error);
    return NextResponse.json(
      { error: "Export failed", success: false },
      { status: 500 }
    );
  }
}

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

function formatContent(content: string, type: string): string {
  const lines = content.split("\n").filter((line) => line.trim());
  let html = "";
  let numberCounter = 1;

  for (const line of lines) {
    const trimmed = line.trim();
    const escaped = escapeHtml(trimmed);

    // Heading (ends with :)
    if (escaped.endsWith(":") && escaped.length > 2) {
      html += `<div class="heading-item">${escaped}</div>`;
    }
    // Bullet point
    else if (escaped.startsWith("•") || escaped.startsWith("-")) {
      const text = escaped.replace(/^[•-]\s*/, "");
      html += `<div class="bullet-item">${text}</div>`;
    }
    // Numbered item
    else if (/^\d+\.\s/.test(escaped)) {
      const text = escaped.replace(/^\d+\.\s*/, "");
      html += `<div class="number-item">${text}</div>`;
    }
    // Regular paragraph
    else {
      html += `<div class="paragraph">${escaped}</div>`;
    }
  }

  return html;
}
