import { Document, Packer, Paragraph, AlignmentType, HeadingLevel } from "docx";

type Report = {
  problemBreakdown: string;
  stakeholders: string;
  solution: string;
  actionPlan: string;
};

function parseContentToSections(content: string): Paragraph[] {
  const lines = content.split("\n").filter((line) => line.trim());
  const paragraphs: Paragraph[] = [];
  let numberingIndex = 1;

  for (const line of lines) {
    const trimmedLine = line.trim();

    // Heading (ends with :)
    if (trimmedLine.endsWith(":") && trimmedLine.length > 2) {
      paragraphs.push(
        new Paragraph({
          text: trimmedLine.replace(/:$/, ""),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 100 },
          bold: true,
        })
      );
    }
    // Bullet point
    else if (trimmedLine.startsWith("•") || trimmedLine.startsWith("-")) {
      paragraphs.push(
        new Paragraph({
          text: trimmedLine.replace(/^[•-]\s*/, ""),
          spacing: { after: 80 },
          bullet: {
            level: 0,
          },
        })
      );
    }
    // Numbered item - use standard numbering
    else if (/^\d+\.\s/.test(trimmedLine)) {
      const text = trimmedLine.replace(/^\d+\.\s*/, "");
      paragraphs.push(
        new Paragraph({
          text: text,
          spacing: { after: 80 },
          numPr: {
            ilvl: 0,
            numId: 1,
          },
        })
      );
    }
    // Regular paragraph
    else if (trimmedLine) {
      paragraphs.push(
        new Paragraph({
          text: trimmedLine,
          spacing: { after: 100 },
        })
      );
    }
  }

  return paragraphs;
}

export async function POST(req: Request) {
  try {
    const { report, problemStatement, timestamp } = await req.json();

    if (!report || !problemStatement) {
      return new Response(JSON.stringify({ error: "Missing report data" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const sections = [
      // Title
      new Paragraph({
        text: "Strategic Planning Report",
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: { before: 200, after: 100 },
        bold: true,
      }),

      // Problem Statement
      new Paragraph({
        text: problemStatement,
        alignment: AlignmentType.CENTER,
        spacing: { after: 100 },
        italics: true,
      }),

      // Date
      new Paragraph({
        text: `Generated: ${new Date(timestamp).toLocaleDateString()}`,
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
        size: 20,
      }),

      // TOC
      new Paragraph({
        text: "Table of Contents",
        heading: HeadingLevel.HEADING_2,
        spacing: { after: 100 },
      }),
      new Paragraph({
        text: "1. Problem Breakdown",
        spacing: { after: 50 },
      }),
      new Paragraph({
        text: "2. Key Stakeholders",
        spacing: { after: 50 },
      }),
      new Paragraph({
        text: "3. Solution Approach",
        spacing: { after: 50 },
      }),
      new Paragraph({
        text: "4. Action Plan",
        spacing: { after: 200 },
      }),

      // Page Break
      new Paragraph({
        text: "",
        pageBreakBefore: true,
      }),

      // Problem Breakdown Section
      new Paragraph({
        text: "Problem Breakdown",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 100, after: 100 },
      }),
      ...parseContentToSections(report.problemBreakdown),

      // Page Break
      new Paragraph({
        text: "",
        pageBreakBefore: true,
      }),

      // Stakeholders Section
      new Paragraph({
        text: "Key Stakeholders",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 100, after: 100 },
      }),
      ...parseContentToSections(report.stakeholders),

      // Page Break
      new Paragraph({
        text: "",
        pageBreakBefore: true,
      }),

      // Solution Section
      new Paragraph({
        text: "Solution Approach",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 100, after: 100 },
      }),
      ...parseContentToSections(report.solution),

      // Page Break
      new Paragraph({
        text: "",
        pageBreakBefore: true,
      }),

      // Action Plan Section with proper numbering
      new Paragraph({
        text: "Action Plan",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 100, after: 100 },
      }),
      ...parseContentToSections(report.actionPlan),

      // Footer
      new Paragraph({
        text: "",
        spacing: { before: 200 },
      }),
      new Paragraph({
        text: "Generated by AI Planning Agent",
        alignment: AlignmentType.CENTER,
        spacing: { after: 50 },
        size: 20,
      }),
      new Paragraph({
        text: "Strategic planning made simple",
        alignment: AlignmentType.CENTER,
        size: 20,
      }),
    ];

    const doc = new Document({
      sections: [
        {
          children: sections,
          properties: {
            page: {
              margins: {
                top: 1440,
                right: 1440,
                bottom: 1440,
                left: 1440,
              },
            },
          },
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);

    if (!buffer || buffer.length === 0) {
      throw new Error("Failed to generate DOCX buffer");
    }

    return new Response(buffer, {
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="strategic-report-${Date.now()}.docx"`,
        "Content-Length": buffer.length.toString(),
      },
    });
  } catch (error) {
    console.error("DOCX export error:", error);
    return new Response(
      JSON.stringify({
        error: "Failed to export DOCX",
        details: error instanceof Error ? error.message : "Unknown error",
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
